# Generated by Django 5.2.5 on 2025-08-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
